name: 🐍 Generate Snake Animation

# Trigger workflow daily and manually
on:
  schedule:
    - cron: "0 0 * * *"   # প্রতিদিন রাত 12 টায়
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Node (required by snk)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Generate Snake SVG
      - name: Generate Snake Contribution SVG
        uses: Platane/snk@v3
        with:
          github_user_name: shahinalam10
          outputs: github-contribution-grid-snake.svg
          theme: dark

      # Push to output branch
      - name: Push SVG to output branch
        uses: actions/configure-pages@v3
      - name: Commit SVG
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B output
          mkdir -p dist
          mv github-contribution-grid-snake.svg dist/
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update Snake Animation"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
